#language: objective-c  #1
#osx_image: xcode7.3 #2
#xcode_project: DSGrowingTextView.xcodeproj
#xcode_scheme: DSGrowingTextView #4
#xcode_sdk: iphonesimulator #5
 #   CODE_SIGN_IDENTITY=""
  #  CODE_SIGNING_REQUIRED=NO
  
language: objective-c
osx_image: xcode7.3 
script:
  - xctool -workspace DSGrowingTextView.xcworkspace -scheme DSGrowingTextView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace DSGrowingTextView.xcworkspace -scheme DSGrowingTextView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
