# http://docs.travis-ci.com/user/languages/objective-c/
# https://github.com/facebook/xctool

language: objective-c

osx_image: xcode7.3

xcode_scheme: DSGrowingTextView 
#podfile: DSGrowingTextView/Podfile
# xcode_sdk: iphonesimulator9.0

script:

  xctool
  -workspace DSGrowingTextView.xcworkspace
  -scheme DSGrowingTextView
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build 
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
